### ISSUE TITLE
scESCC_Ours.md提到的Figshare链接可以提供一下吗

### ISSUE THREAD

**Issue by Tim0thy1** [pangxueyu233/CCI-in-ESCC#1]
大神你好, 
我想通过数据复现一下文章的fig1, 其中的数据说能在Figshare上查找, 但我没找到链接呢? 可以提供scESCC_map.rds一下吗?

另外我看你的code里面XY_FeaturePlot 是不是自己写的函数, 要source才能用, 这个script能否也分享一下呢?

**Comment by pangxueyu233** [comment]
好的。理论上GEO数据库应该有这些文件，可能是他们不能对应单独的处理文件和原始文件。不过我已经重新进行了处理。
`MyBestFunction_scRNA.R`和`Pseudo_CNV_series.R`文件我重新上传到了这个仓库下的`CCI-Identify/extended_tools`。你可以下载这个库之后，查看和载入，载入方法可以参考`scESCC_Ours.md`
`Processed_datafiles`尤其是`*.md`文件中我提到的所有`.rds`文件我都上传至[Figshare](https://figshare.com/articles/dataset/CCI-in-ESCC/19609548), 你可以通过点击[这里](https://figshare.com/articles/dataset/CCI-in-ESCC/19609548).
以上信息我将会在`README`文件中更新

Yeah, the `MyBestFunction_scRNA.R` and `Pseudo_CNV_series.R` mentioned in `scESCC_Ours.md` had been updated and stored in `CCI-in-ESCC/CCI-Identify/extended_tools`. You could get them by `clone` this git. 
And the `Processed_datafiles`, especially the `.rds` files, mentioned in `*.md` files had been submitted into [Figshare](https://figshare.com/articles/dataset/CCI-in-ESCC/19609548). And you could get them by clicking [here](https://figshare.com/articles/dataset/CCI-in-ESCC/19609548). 

Xiangyu Pan
