### ISSUE TITLE
Contradictory records in GEOdataset and article

### ISSUE THREAD

**Issue by zyh4482** [pangxueyu233/CCI-in-ESCC#2]
Hi. 

I was trying to perform single cell analysis on your cohort. I noticed that the library was constructed by 10x 3' v3 library kit, according to your article. 

> The library was prepared by using the 10× genomics platform, Chromium Single Cell 3′ Reagent Kits v3, following the manufactory’s protocol. 

But the experimental records in SRA seems to be contradictory. For instance, [SRR16952877](https://www.ncbi.nlm.nih.gov/sra/SRX13144556[accn]) described the experimental protocol: 

> Follwed by v2 protocol of chemistry of the 3' scRNA-seq 10X genomics platform

I tried to dig into the raw fastq, but I could not be sure about the R1 UMI_barcode pattern. It would be very kind of you to enlight me which library protocol was used in this cohort. 

Thank you.

**Comment by pangxueyu233** [comment]
Hi, 
You could use the `Single Cell 3' v2` for your following analysis. Our scRNA data are generated from `Single Cell 3' v2` with alignment with `hg19`. And the SRA page records the right information of library construction. Here is the `patient6-cancer`'s report of cellranger.
![image](https://user-images.githubusercontent.com/40414477/185259643-8c5e923e-0835-4e29-8de2-6ced46138e29.png)

**Comment by zyh4482** [comment]
Thank you so much!
